title:             Exceptional Mirrors
tagline:           'Tales from an abandonware dev e-loper'
url:               http://mirrors.link
baseurl:           ''
permalink:         /posts/:title
timezone:          'UTC'
excerpt_separator: "<!--more-->"
future:            true
# I use the pagination not for the actual pagination, but for taking care of hiding
# posts with `hidden: true` in the front matter, so I set this value arbitrarily high.
paginate:          100

author:
  name:           Rafał Cieślak
  twitter_handle: Ravicious

exclude:      [lanyon-license.md, Gemfile, Gemfile.lock, CNAME]

kramdown:
  input: GFM

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
